name: GitHub Pages

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    name: Build
    permissions:
      contents: read
    runs-on: ubuntu-slim
    env:
      NODE_ENV: production
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: lts
          cache: true

      - name: Build
        run: deno --allow-env --allow-net --allow-write ./main.js

      - name: Upload
        uses: actions/upload-pages-artifact@v3
        with:
          path: out/
  deploy:
    name: Deploy
    permissions:
      pages: write
      id-token: write
    needs: build
    runs-on: ubuntu-slim
    environment:
      name: github-pages
      url: ${{ steps.deploy-pages.outputs.page_url }}
    steps:
      - name: Deploy GitHub Pages site
        id: deploy-pages
        uses: actions/deploy-pages@v4
